# Generated by Django 3.2.5 on 2021-07-22 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_backend_django', '0003_alter_todoitem_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['order']},
        ),
    ]
